### ISSUE TITLE
Could you share your dataset?

### ISSUE THREAD

**Issue by kevinlemon** [Pranshu258/cwa#1]
Nice work.
Will you share the dataset?

**Comment by Pranshu258** [comment]
The data that we have used can be obtained by sending a request to Alexandre Alahi at alex.email@gmail.com. He is one of the authors of the paper "Socially-aware Large-scale Crowd Forecasting" and they are the owners of this dataset.

**Comment by Pranshu258** [comment]
Unfortunately, I don't have a copy of the dataset at this moment, please contact Alexandre Alahi at his email for help.

**Comment by kevinlemon** [comment]
Thank you.
We have sent an email a week ago, but there is no reply.
-------------------Email Information-------------------------
From "meng-li18@mails.tsinghua.edu.cn" to  "alex.email@gmail.com"  2019-11-16 10:00:13
Subject: Requesting for the data of Crowd behavior analysis

**Comment by kevinlemon** [comment]
Where can I find the dataset?
Still no reply from Alex's email
