### ISSUE TITLE
Where can I find the dataset?

### ISSUE THREAD

**Issue by kevinlemon** [Pranshu258/cwa#2]
Where can I find the dataset?
Still no reply from Alex's email

_Originally posted by @kevinlemon in https://github.com/Pranshu258/Crowd_Behavior_Analysis/issues/1#issuecomment-558636238_

**Comment by Pranshu258** [comment]
Please try emailing to both the authors: 
alahi@cs.stanford.edu
vigneshr@cs.stanford.edu

I am not aware of any website on the internet where this data is available, luckily when we mailed Alex, he replied (it was 3 years ago) and we got the dataset. 

As of today, I neither have a copy of the dataset nor the machine on which we implemented this project, so I wouldn't be able to help. Sorry. 

If nothing works, you may try to generate a synthetic dataset on your own. If that helps

**Comment by kevinlemon** [comment]
Thank you so much!
